{
 "title": "Telemetry ESP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Comandi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Freno",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "commands",
     "select": [
      [
       { "params": [ "brake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    },
    {
     "alias": "Acceleratore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "commands",
     "select": [
      [
       { "params": [ "throttle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    },
    {
     "alias": "Sterzo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "commands",
     "select": [
      [
       { "params": [ "steering" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Scarico",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "exhaust_temp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Posizione",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gps",
     "query": "SELECT \"lat\"::float / 10000000  AS \"lat\", \"long\"::float / 10000000  AS \"lon\" FROM \"gps\" WHERE (\"device\" = 'Telemetry_ESP32_0001') AND $timeFilter",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "lat" ], "type": "alias" }
      ],
      [
       { "params": [ "long" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "lon" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Accelerazione",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "accG" }
   ],
   "targets": [
    {
     "alias": "Asse X",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "accelerometer",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    },
    {
     "alias": "Asse Y",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "accelerometer",
     "select": [
      [
       { "params": [ "y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    },
    {
     "alias": "Asse Z",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "accelerometer",
     "select": [
      [
       { "params": [ "z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Velocità",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "alias": "Velocità",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gps",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 0.0036" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "ADC",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "adc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    },
    {
     "alias": "Tensione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Altitudine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "Velocità",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gps",
     "select": [
      [
       { "params": [ "alt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Telemetry_ESP32_0001" }
     ]
    }
   ]
  }
 ]
}